###REGISTER A USER
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email":"gamesmy177@gmail.com",
    "password": "password",
    "firstName": "Daniel",
    "lastName": "Kitheka",
    "phoneNumber": "+254112272253"
}

###LOGIN A USER
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"earljoe06@gmail.com",
    "password": "12345678"
}

###CHANGE PASSWORD
POST http://localhost:3000/api/auth/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1N2U5NjgwOC1lNWE5LTRjYjYtOTAwZC04NDBkNGE3ODE3ZmYiLCJlbWFpbCI6ImdhbWVzbXkxNzdAZ21haWwuY29tIiwicGhvbmVOdW1iZXIiOiIrMjU0MTEyMjcyMjUzIiwiZmlyc3ROYW1lIjoiRGFuaWVsIiwibGFzdE5hbWUiOiJLaXRoZWthIiwicm9sZSI6IkFUVEVOREVFIiwiaWF0IjoxNzIxMzg1OTU5LCJleHAiOjE3MjE0MDAzNTl9.jaXh4aJFgIwy3XkY7g5onENcUZ2edMje57k0vcpB3Jg
Content-Type: application/json

{
    "userId": "57e96808-e5a9-4cb6-900d-840d4a7817ff",
    "oldPassword": "password",
    "newPassword": "newpassword"
}

###REQUEST PASSWORD RESET
POST http://localhost:3000/api/auth/request-password-reset
Content-Type: application/json

{
    "email":"angelakolwa@gmail.com"
}

###RESET PASSWORD
POST http://localhost:3000/api/auth/reset-password
Content-Type: application/json

{
    "resetToken": "6550",
    "newPassword": "newpassword"
}