POST http://localhost:3000/api/booking/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzUyMTliMS1lY2UwLTQ0YWUtYWFjZS01MGQzNDQ3ZjlhNDIiLCJlbWFpbCI6InJpZ2h0bWVuY3VzdG9tekBnbWFpbC5jb20iLCJwaG9uZU51bWJlciI6IisyNTQxMTIyNzIyNTMiLCJmaXJzdE5hbWUiOiJNYXJrIiwibGFzdE5hbWUiOiJOZGl3aWdhIiwicm9sZSI6IkFUVEVOREVFIiwiaWF0IjoxNzIxMjA5Nzk3LCJleHAiOjE3MjEyMjQxOTd9.1q_SrWAWQxE4ZiYyyvG5_nvhVdnxhc0Kdw7av4rbyG4
Content-Type: application/json

{
  "userId": "675219b1-ece0-44ae-aace-50d3447f9a42",
  "eventId": "736a48d0-e08d-4995-b6de-b471073e1094",
  "tickets": [
    {
      "ticketId": "84f9763b-0eac-4dbf-a54e-7724fa6e30b5",
      "quantity": 2
    },
    {
      "ticketId": "7fd8af1c-1bec-43c9-8447-650171675c19",
      "quantity": 1
    }
  ],
  "attendeeDetails": [
    {
      "firstName": "Wekesa",
      "lastName": "Kadima",
      "ticketType": "VIP"
    },
    {
      "firstName": "Mak",
      "lastName": "Ndigi",
      "ticketType": "Regular"
    },
    {
      "firstName": "Mwangi",
      "lastName": "Ndungu",
      "ticketType": "Regular"
    }

  ]
}


###VERIFY BOOKING
GET http://localhost:3000/api/booking/verify/258ca02a-9416-47ff-88bf-2e48738c2876
Authorization: Bearer 
Content-Type: application/json

{
    "verificationCode": "XX2RKYHV7B"
}

###GET ALL BOOKINGS
GET http://localhost:3000/api/booking/all

