POST http://localhost:3000/api/booking/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyNDdkNGRjYS1iZGU2LTQwNzctOTcxNC0xYTA1OTNhY2IwNTkiLCJlbWFpbCI6ImVhcmxqb2UwNkBnbWFpbC5jb20iLCJwaG9uZU51bWJlciI6IjAxMTIyNzIyNTAiLCJmaXJzdE5hbWUiOiJFYXJsam9lIiwibGFzdE5hbWUiOiJLYWRpbWEiLCJyb2xlIjoiQVRURU5ERUUiLCJpYXQiOjE3MjEzODY4NTcsImV4cCI6MTcyMTQwMTI1N30.NSiA4oLN4eSk5pBVARr9Qpltz1Xgzw2IwBsCnLe5kG4
Content-Type: application/json

{
  "userId": "675219b1-ece0-44ae-aace-50d3447f9a42",
  "eventId": "736a48d0-e08d-4995-b6de-b471073e1094",
  "tickets": [
    {
      "ticketId": "84f9763b-0eac-4dbf-a54e-7724fa6e30b5",
      "quantity": 2
    },
    {
      "ticketId": "7fd8af1c-1bec-43c9-8447-650171675c19",
      "quantity": 1
    }
  ],
  "attendeeDetails": [
    {
      "firstName": "John",
      "lastName": "Doe",
      "ticketType": "VIP"
    },
    {
      "firstName": "Jane",
      "lastName": "Doe",
      "ticketType": "Regular"
    },
    {
      "firstName": "Daniel",
      "lastName": "Kitheka",
      "ticketType": "Regular"
    }

  ]
}


###VERIFY BOOKING
POST  http://localhost:3000/api/booking/verify/ffc73660-bd1f-4b7d-a139-a5adc09cf1a1
Authorization: Bearer 
Content-Type: application/json

{
    "verificationCode": "51POM2R3EQ"
}

###GET ALL BOOKINGS
GET http://localhost:3000/api/booking/all


###GET BOOKING BY USER ID
GET http://localhost:3000/api/booking/user/675219b1-ece0-44ae-aace-50d3447f9a42

