###CREATE A CATEGORY
POST http://localhost:3000/api/category/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxZjFkMjdiMy0zMWY4LTQ0YjktYmU0NC0yNTA2YTVmOTU1YTEiLCJlbWFpbCI6ImVhcmxqb2UwNkBvdXRsb29rLmNvbSIsInBob25lTnVtYmVyIjoiMDExMjI3MjI1MCIsImZpcnN0TmFtZSI6IkVhcmxqb2UiLCJsYXN0TmFtZSI6IkthZGltYSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcyMTM4NjE3NiwiZXhwIjoxNzIxNDAwNTc2fQ.Lt0VuDYdF5xW6vG-m4p591z6wnPQnv0AkULRn0jFiYo
Content-Type: application/json

{
    "name": "School"
}

###GET ALL CATEGORIES
GET http://localhost:3000/api/category/all

###GET CATEGORY BY ID
GET http://localhost:3000/api/category/0a7ec11b-2789-4175-84aa-d3d77bec95c3

###UPDATE A CATEGORY
PUT http://localhost:3000/api/category/0a7ec11b-2789-4175-84aa-d3d77bec95c3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxZjFkMjdiMy0zMWY4LTQ0YjktYmU0NC0yNTA2YTVmOTU1YTEiLCJlbWFpbCI6ImVhcmxqb2UwNkBvdXRsb29rLmNvbSIsInBob25lTnVtYmVyIjoiMDExMjI3MjI1MCIsImZpcnN0TmFtZSI6IkVhcmxqb2UiLCJsYXN0TmFtZSI6IkthZGltYSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcyMTM4NjE3NiwiZXhwIjoxNzIxNDAwNTc2fQ.Lt0VuDYdF5xW6vG-m4p591z6wnPQnv0AkULRn0jFiYo
Content-Type: application/json

{
    "name": "School up"
}

###DELETE A CATEGORY
DELETE http://localhost:3000/api/category/30a0ae67-ad0b-43f9-afd1-8b2894659c29
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkYTQ1MGE0LTg2ZTItNGRkZC04YjhjLTZhNTIxOTU3ZjhhNyIsImVtYWlsIjoiZWFybGpvZTA2QG91dGxvb2suY29tIiwicGhvbmVOdW1iZXIiOiIrMjU0MTEyMjcyMjUwIiwicGFzc3dvcmRIYXNoIjoiJDJiJDEwJG5HbTQ1dDM3ZVM4QXllQlIvVHN0LmV6emkxalVGbU51WDU3VXNTVjd5U1IzaHlLbE8uOVVlIiwiZmlyc3ROYW1lIjoiRWFybGpvZSIsImxhc3ROYW1lIjoiS2FkaW1hIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9zdGF0aWMudmVjdGVlenkuY29tL3N5c3RlbS9yZXNvdXJjZXMvcHJldmlld3MvMDA1LzU0NS8zMzUvbm9uXzJ4L3VzZXItc2lnbi1pY29uLXBlcnNvbi1zeW1ib2wtaHVtYW4tYXZhdGFyLWlzb2xhdGVkLW9uLXdoaXRlLWJhY2tvZ3J1bmQtdmVjdG9yLmpwZyIsInJvbGUiOiJBRE1JTiIsIm1hbmFnZXJSZXF1ZXN0U3RhdHVzIjoiUEVORElORyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInJlc2V0VG9rZW4iOm51bGwsInJlc2V0VG9rZW5FeHBpcnkiOm51bGwsImlhdCI6MTcyMDI3NTE2NSwiZXhwIjoxNzIwMjc4NzY1fQ.fPeLWjuUxISWdtodZOFuVC6TykSfqF1T7i_L4pPtJtQ
