@baseUrl = http://localhost:3000/api/event
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MzI1ZGI2ZC0yYTc3LTQ3YWMtYjFhNC0wYjc4ZDc2YjdjN2UiLCJlbWFpbCI6ImFuZ2VsYWtvbHdhQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDExNTQ2Nzg5MiIsImZpcnN0TmFtZSI6IkFuZ2VsYSIsImxhc3ROYW1lIjoiS29sd2EiLCJyb2xlIjoiRVZFTlRfTUFOQUdFUiIsImlhdCI6MTcyMTM4NjQ0NSwiZXhwIjoxNzIxNDAwODQ1fQ.fJfQKw0xJ2iMYstpMK9xItxar9DK2HN04iiJujVD6f0

### Create a new event with tickets
POST {{baseUrl}}/create
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Camp Ndunda Trip
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

A weekend of great music and fun
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="date"

2023-07-15T18:00:00Z
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="location"

Central Park, New York
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="categoryId"

0a7ec11b-2789-4175-84aa-d3d77bec95c3
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="poster"; filename="clubMbuzi.png"
Content-Type: image/png

< /home/earljoe/Downloads/clubMbuzi.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="tickets"
Content-Type: application/json

[{"type": "Regular", "price": 50, "quantity": 1000}, {"type": "VIP", "price": 150, "quantity": 100}]
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Get all events
GET {{baseUrl}}/all

### Get a specific event
GET {{baseUrl}}/d629e443-7c53-48a4-93b3-b44d487da789

### Update an event
PUT {{baseUrl}}/update/f2636584-8f70-4208-ae03-ea337420e4d9
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "Updated Summer Music Festival",
  "description": "A weekend of great music and mad fun",
  "date": "2023-07-15T18:00:00Z",
  "location": "Chuka",
  "categoryId": "0a7ec11b-2789-4175-84aa-d3d77bec95c3",
  "tickets": "[{\"type\": \"General Admission\", \"price\": 5000, \"quantity\": 1000}, {\"type\": \"VIP\", \"price\": 10000, \"quantity\": 100}]"
}

###GET all events in a category
GET {{baseUrl}}/category/0a7ec11b-2789-4175-84aa-d3d77bec95c3


###GET EVENTS BY Manager
GET {{baseUrl}}/manager/5de20edc-36f1-4388-a2ec-2dc61a571e10

### Get events by location
GET {{baseUrl}}/location/Chuka
Authorization: Bearer {{authToken}}
Content-Type: application/json


### Update event poster
PUT {{baseUrl}}/update-poster/f2636584-8f70-4208-ae03-ea337420e4d9
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="poster"; filename="clubMbuzi.png"
Content-Type: image/png

< /home/earljoe/Downloads/clubMbuzi.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Delete an event
DELETE {{baseUrl}}/f2636584-8f70-4208-ae03-ea337420e4d9
Authorization: Bearer {{authToken}}

