###GET USER BY ID
GET http://localhost:3000/api/user/8bd9ed83-e8df-4913-af10-7855bef50e67


###GET USER BY EMAIL
GET http://localhost:3000/api/user/email/angelakolwa@gmail.com


###GET ALL USERS
GET http://localhost:3000/api/user/all/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkYTQ1MGE0LTg2ZTItNGRkZC04YjhjLTZhNTIxOTU3ZjhhNyIsImVtYWlsIjoiZWFybGpvZTA2QG91dGxvb2suY29tIiwicGhvbmVOdW1iZXIiOiIrMjU0MTEyMjcyMjUwIiwicGFzc3dvcmRIYXNoIjoiJDJiJDEwJG5HbTQ1dDM3ZVM4QXllQlIvVHN0LmV6emkxalVGbU51WDU3VXNTVjd5U1IzaHlLbE8uOVVlIiwiZmlyc3ROYW1lIjoiRWFybGpvZSIsImxhc3ROYW1lIjoiS2FkaW1hIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9zdGF0aWMudmVjdGVlenkuY29tL3N5c3RlbS9yZXNvdXJjZXMvcHJldmlld3MvMDA1LzU0NS8zMzUvbm9uXzJ4L3VzZXItc2lnbi1pY29uLXBlcnNvbi1zeW1ib2wtaHVtYW4tYXZhdGFyLWlzb2xhdGVkLW9uLXdoaXRlLWJhY2tvZ3J1bmQtdmVjdG9yLmpwZyIsInJvbGUiOiJBRE1JTiIsIm1hbmFnZXJSZXF1ZXN0U3RhdHVzIjoiUEVORElORyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInJlc2V0VG9rZW4iOm51bGwsInJlc2V0VG9rZW5FeHBpcnkiOm51bGwsImlhdCI6MTcyMDI2MjY4OSwiZXhwIjoxNzIwMjY2Mjg5fQ.IGkzifhR5_UWJ77j2z1-s8A9yp92M6B0nl-FMYVADc4

###UPDATE USER
PUT http://localhost:3000/api/user/update/5de20edc-36f1-4388-a2ec-2dc61a571e10
Content-Type: application/json

{
    "email":"earljoe06@gmail.com"
}

###REQUEST MANAGER ROLE
POST http://localhost:3000/api/user/request-manager
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkZTIwZWRjLTM2ZjEtNDM4OC1hMmVjLTJkYzYxYTU3MWUxMCIsImVtYWlsIjoiam9obmRvZUBvdXRsb29rLmNvbSIsInBob25lTnVtYmVyIjoiKzI1NDExMjI3MjI1MCIsInBhc3N3b3JkSGFzaCI6IiQyYiQxMCRqWlBadW9td0UvTHR0V0VFTGNlOG0ud041R0hPOHAzY0JLOC9TUnNGUDVnTUU0VERaU3d5UyIsImZpcnN0TmFtZSI6IkpPaG4iLCJsYXN0TmFtZSI6IkthZGltYSIsImF2YXRhclVybCI6Imh0dHBzOi8vc3RhdGljLnZlY3RlZXp5LmNvbS9zeXN0ZW0vcmVzb3VyY2VzL3ByZXZpZXdzLzAwNS81NDUvMzM1L25vbl8yeC91c2VyLXNpZ24taWNvbi1wZXJzb24tc3ltYm9sLWh1bWFuLWF2YXRhci1pc29sYXRlZC1vbi13aGl0ZS1iYWNrb2dydW5kLXZlY3Rvci5qcGciLCJyb2xlIjoiQVRURU5ERUUiLCJtYW5hZ2VyUmVxdWVzdFN0YXR1cyI6IlBFTkRJTkciLCJjcmVhdGVkQXQiOiIyMDI0LTA3LTA2VDExOjMwOjQxLjgzMloiLCJ1cGRhdGVkQXQiOiIyMDI0LTA3LTA2VDExOjMwOjQxLjgzMloiLCJyZXNldFRva2VuIjpudWxsLCJyZXNldFRva2VuRXhwaXJ5IjpudWxsLCJpYXQiOjE3MjAyNjU0NzksImV4cCI6MTcyMDI2OTA3OX0.09ulmu_ESAWz_6MOS68G6PsoZ4kSxhb1TOvlUC7IpZM
Content-Type: application/json

{
    "userId": "5de20edc-36f1-4388-a2ec-2dc61a571e10"
}

###APPROVE MANAGER ROLE
POST http://localhost:3000/api/user/approve-manager
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkYTQ1MGE0LTg2ZTItNGRkZC04YjhjLTZhNTIxOTU3ZjhhNyIsImVtYWlsIjoiZWFybGpvZTA2QG91dGxvb2suY29tIiwicGhvbmVOdW1iZXIiOiIrMjU0MTEyMjcyMjUwIiwicGFzc3dvcmRIYXNoIjoiJDJiJDEwJG5HbTQ1dDM3ZVM4QXllQlIvVHN0LmV6emkxalVGbU51WDU3VXNTVjd5U1IzaHlLbE8uOVVlIiwiZmlyc3ROYW1lIjoiRWFybGpvZSIsImxhc3ROYW1lIjoiS2FkaW1hIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9zdGF0aWMudmVjdGVlenkuY29tL3N5c3RlbS9yZXNvdXJjZXMvcHJldmlld3MvMDA1LzU0NS8zMzUvbm9uXzJ4L3VzZXItc2lnbi1pY29uLXBlcnNvbi1zeW1ib2wtaHVtYW4tYXZhdGFyLWlzb2xhdGVkLW9uLXdoaXRlLWJhY2tvZ3J1bmQtdmVjdG9yLmpwZyIsInJvbGUiOiJBRE1JTiIsIm1hbmFnZXJSZXF1ZXN0U3RhdHVzIjoiUEVORElORyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInJlc2V0VG9rZW4iOm51bGwsInJlc2V0VG9rZW5FeHBpcnkiOm51bGwsImlhdCI6MTcyMDI2NjM1NSwiZXhwIjoxNzIwMjY5OTU1fQ.JoVNyc1VGr3QiUDL9XrD50ngHm-7VaGCzXLcEzBuYko
Content-Type: application/json

{
    "userId": "5de20edc-36f1-4388-a2ec-2dc61a571e10"
}

###GET MANAGER REQUESTS
GET http://localhost:3000/api/user/manager/requests
Authorization: Bearer 

###REJECT MANAGER ROLE
POST http://localhost:3000/api/user/reject-manager
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkYTQ1MGE0LTg2ZTItNGRkZC04YjhjLTZhNTIxOTU3ZjhhNyIsImVtYWlsIjoiZWFybGpvZTA2QG91dGxvb2suY29tIiwicGhvbmVOdW1iZXIiOiIrMjU0MTEyMjcyMjUwIiwicGFzc3dvcmRIYXNoIjoiJDJiJDEwJG5HbTQ1dDM3ZVM4QXllQlIvVHN0LmV6emkxalVGbU51WDU3VXNTVjd5U1IzaHlLbE8uOVVlIiwiZmlyc3ROYW1lIjoiRWFybGpvZSIsImxhc3ROYW1lIjoiS2FkaW1hIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9zdGF0aWMudmVjdGVlenkuY29tL3N5c3RlbS9yZXNvdXJjZXMvcHJldmlld3MvMDA1LzU0NS8zMzUvbm9uXzJ4L3VzZXItc2lnbi1pY29uLXBlcnNvbi1zeW1ib2wtaHVtYW4tYXZhdGFyLWlzb2xhdGVkLW9uLXdoaXRlLWJhY2tvZ3J1bmQtdmVjdG9yLmpwZyIsInJvbGUiOiJBRE1JTiIsIm1hbmFnZXJSZXF1ZXN0U3RhdHVzIjoiUEVORElORyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInJlc2V0VG9rZW4iOm51bGwsInJlc2V0VG9rZW5FeHBpcnkiOm51bGwsImlhdCI6MTcyMDI2MjY4OSwiZXhwIjoxNzIwMjY2Mjg5fQ.IGkzifhR5_UWJ77j2z1-s8A9yp92M6B0nl-FMYVADc4
Content-Type: application/json

{
    "userId": "5de20edc-36f1-4388-a2ec-2dc61a571e10"
}
###GET ALL MANAGERS
GET http://localhost:3000/api/user/manager/all

###CHANGE ROLE
POST http://localhost:3000/api/user/change-role
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkYTQ1MGE0LTg2ZTItNGRkZC04YjhjLTZhNTIxOTU3ZjhhNyIsImVtYWlsIjoiZWFybGpvZTA2QG91dGxvb2suY29tIiwicGhvbmVOdW1iZXIiOiIrMjU0MTEyMjcyMjUwIiwicGFzc3dvcmRIYXNoIjoiJDJiJDEwJG5HbTQ1dDM3ZVM4QXllQlIvVHN0LmV6emkxalVGbU51WDU3VXNTVjd5U1IzaHlLbE8uOVVlIiwiZmlyc3ROYW1lIjoiRWFybGpvZSIsImxhc3ROYW1lIjoiS2FkaW1hIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9zdGF0aWMudmVjdGVlenkuY29tL3N5c3RlbS9yZXNvdXJjZXMvcHJldmlld3MvMDA1LzU0NS8zMzUvbm9uXzJ4L3VzZXItc2lnbi1pY29uLXBlcnNvbi1zeW1ib2wtaHVtYW4tYXZhdGFyLWlzb2xhdGVkLW9uLXdoaXRlLWJhY2tvZ3J1bmQtdmVjdG9yLmpwZyIsInJvbGUiOiJBRE1JTiIsIm1hbmFnZXJSZXF1ZXN0U3RhdHVzIjoiUEVORElORyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInJlc2V0VG9rZW4iOm51bGwsInJlc2V0VG9rZW5FeHBpcnkiOm51bGwsImlhdCI6MTcyMDI2MjY4OSwiZXhwIjoxNzIwMjY2Mjg5fQ.IGkzifhR5_UWJ77j2z1-s8A9yp92M6B0nl-FMYVADc4
Content-Type: application/json

{
    "userId": "8bd9ed83-e8df-4913-af10-7855bef50e67",
    "newRole": "ADMIN"
}

###GET USER STATS
GET http://localhost:3000/api/user/u/stats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkYTQ1MGE0LTg2ZTItNGRkZC04YjhjLTZhNTIxOTU3ZjhhNyIsImVtYWlsIjoiZWFybGpvZTA2QG91dGxvb2suY29tIiwicGhvbmVOdW1iZXIiOiIrMjU0MTEyMjcyMjUwIiwicGFzc3dvcmRIYXNoIjoiJDJiJDEwJG5HbTQ1dDM3ZVM4QXllQlIvVHN0LmV6emkxalVGbU51WDU3VXNTVjd5U1IzaHlLbE8uOVVlIiwiZmlyc3ROYW1lIjoiRWFybGpvZSIsImxhc3ROYW1lIjoiS2FkaW1hIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9zdGF0aWMudmVjdGVlenkuY29tL3N5c3RlbS9yZXNvdXJjZXMvcHJldmlld3MvMDA1LzU0NS8zMzUvbm9uXzJ4L3VzZXItc2lnbi1pY29uLXBlcnNvbi1zeW1ib2wtaHVtYW4tYXZhdGFyLWlzb2xhdGVkLW9uLXdoaXRlLWJhY2tvZ3J1bmQtdmVjdG9yLmpwZyIsInJvbGUiOiJBRE1JTiIsIm1hbmFnZXJSZXF1ZXN0U3RhdHVzIjoiUEVORElORyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInJlc2V0VG9rZW4iOm51bGwsInJlc2V0VG9rZW5FeHBpcnkiOm51bGwsImlhdCI6MTcyMDI2MjY4OSwiZXhwIjoxNzIwMjY2Mjg5fQ.IGkzifhR5_UWJ77j2z1-s8A9yp92M6B0nl-FMYVADc4

###SEARCH USERS
#NOT WORKING
GET http://localhost:3000/api/user/s/search-users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkYTQ1MGE0LTg2ZTItNGRkZC04YjhjLTZhNTIxOTU3ZjhhNyIsImVtYWlsIjoiZWFybGpvZTA2QG91dGxvb2suY29tIiwicGhvbmVOdW1iZXIiOiIrMjU0MTEyMjcyMjUwIiwicGFzc3dvcmRIYXNoIjoiJDJiJDEwJG5HbTQ1dDM3ZVM4QXllQlIvVHN0LmV6emkxalVGbU51WDU3VXNTVjd5U1IzaHlLbE8uOVVlIiwiZmlyc3ROYW1lIjoiRWFybGpvZSIsImxhc3ROYW1lIjoiS2FkaW1hIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9zdGF0aWMudmVjdGVlenkuY29tL3N5c3RlbS9yZXNvdXJjZXMvcHJldmlld3MvMDA1LzU0NS8zMzUvbm9uXzJ4L3VzZXItc2lnbi1pY29uLXBlcnNvbi1zeW1ib2wtaHVtYW4tYXZhdGFyLWlzb2xhdGVkLW9uLXdoaXRlLWJhY2tvZ3J1bmQtdmVjdG9yLmpwZyIsInJvbGUiOiJBRE1JTiIsIm1hbmFnZXJSZXF1ZXN0U3RhdHVzIjoiUEVORElORyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInJlc2V0VG9rZW4iOm51bGwsInJlc2V0VG9rZW5FeHBpcnkiOm51bGwsImlhdCI6MTcyMDI2MjY4OSwiZXhwIjoxNzIwMjY2Mjg5fQ.IGkzifhR5_UWJ77j2z1-s8A9yp92M6B0nl-FMYVADc4
Content-Type: application/json

{
    "search": "h"
}

###DELETE USER
DELETE http://localhost:3000/api/user/8bd9ed83-e8df-4913-af10-7855bef50e67
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkYTQ1MGE0LTg2ZTItNGRkZC04YjhjLTZhNTIxOTU3ZjhhNyIsImVtYWlsIjoiZWFybGpvZTA2QG91dGxvb2suY29tIiwicGhvbmVOdW1iZXIiOiIrMjU0MTEyMjcyMjUwIiwicGFzc3dvcmRIYXNoIjoiJDJiJDEwJG5HbTQ1dDM3ZVM4QXllQlIvVHN0LmV6emkxalVGbU51WDU3VXNTVjd5U1IzaHlLbE8uOVVlIiwiZmlyc3ROYW1lIjoiRWFybGpvZSIsImxhc3ROYW1lIjoiS2FkaW1hIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9zdGF0aWMudmVjdGVlenkuY29tL3N5c3RlbS9yZXNvdXJjZXMvcHJldmlld3MvMDA1LzU0NS8zMzUvbm9uXzJ4L3VzZXItc2lnbi1pY29uLXBlcnNvbi1zeW1ib2wtaHVtYW4tYXZhdGFyLWlzb2xhdGVkLW9uLXdoaXRlLWJhY2tvZ3J1bmQtdmVjdG9yLmpwZyIsInJvbGUiOiJBRE1JTiIsIm1hbmFnZXJSZXF1ZXN0U3RhdHVzIjoiUEVORElORyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInJlc2V0VG9rZW4iOm51bGwsInJlc2V0VG9rZW5FeHBpcnkiOm51bGwsImlhdCI6MTcyMDI2MjY4OSwiZXhwIjoxNzIwMjY2Mjg5fQ.IGkzifhR5_UWJ77j2z1-s8A9yp92M6B0nl-FMYVADc4
