###GET USER BY ID
GET http://localhost:3000/api/user/8bd9ed83-e8df-4913-af10-7855bef50e67


###GET USER BY EMAIL
GET http://localhost:3000/api/user/email/angelakolwa@gmail.com


###GET ALL USERS
GET http://localhost:3000/api/user/all/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkYTQ1MGE0LTg2ZTItNGRkZC04YjhjLTZhNTIxOTU3ZjhhNyIsImVtYWlsIjoiZWFybGpvZTA2QG91dGxvb2suY29tIiwicGhvbmVOdW1iZXIiOiIrMjU0MTEyMjcyMjUwIiwicGFzc3dvcmRIYXNoIjoiJDJiJDEwJG5HbTQ1dDM3ZVM4QXllQlIvVHN0LmV6emkxalVGbU51WDU3VXNTVjd5U1IzaHlLbE8uOVVlIiwiZmlyc3ROYW1lIjoiRWFybGpvZSIsImxhc3ROYW1lIjoiS2FkaW1hIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9zdGF0aWMudmVjdGVlenkuY29tL3N5c3RlbS9yZXNvdXJjZXMvcHJldmlld3MvMDA1LzU0NS8zMzUvbm9uXzJ4L3VzZXItc2lnbi1pY29uLXBlcnNvbi1zeW1ib2wtaHVtYW4tYXZhdGFyLWlzb2xhdGVkLW9uLXdoaXRlLWJhY2tvZ3J1bmQtdmVjdG9yLmpwZyIsInJvbGUiOiJBRE1JTiIsIm1hbmFnZXJSZXF1ZXN0U3RhdHVzIjoiUEVORElORyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInJlc2V0VG9rZW4iOm51bGwsInJlc2V0VG9rZW5FeHBpcnkiOm51bGwsImlhdCI6MTcyMDI2MjY4OSwiZXhwIjoxNzIwMjY2Mjg5fQ.IGkzifhR5_UWJ77j2z1-s8A9yp92M6B0nl-FMYVADc4

###UPDATE USER
PUT http://localhost:3000/api/user/update/5de20edc-36f1-4388-a2ec-2dc61a571e10
Content-Type: application/json

{
    "email":"earljoe06@gmail.com"
}

###REQUEST MANAGER ROLE
POST http://localhost:3000/api/user/request-manager
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1N2U5NjgwOC1lNWE5LTRjYjYtOTAwZC04NDBkNGE3ODE3ZmYiLCJlbWFpbCI6ImdhbWVzbXkxNzdAZ21haWwuY29tIiwicGhvbmVOdW1iZXIiOiIrMjU0MTEyMjcyMjUzIiwiZmlyc3ROYW1lIjoiRGFuaWVsIiwibGFzdE5hbWUiOiJLaXRoZWthIiwicm9sZSI6IkFUVEVOREVFIiwiaWF0IjoxNzIxMzg1OTU5LCJleHAiOjE3MjE0MDAzNTl9.jaXh4aJFgIwy3XkY7g5onENcUZ2edMje57k0vcpB3Jg
Content-Type: application/json

{
    "userId": "57e96808-e5a9-4cb6-900d-840d4a7817ff"
}

###APPROVE MANAGER ROLE
POST http://localhost:3000/api/user/approve-manager
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkYTQ1MGE0LTg2ZTItNGRkZC04YjhjLTZhNTIxOTU3ZjhhNyIsImVtYWlsIjoiZWFybGpvZTA2QG91dGxvb2suY29tIiwicGhvbmVOdW1iZXIiOiIrMjU0MTEyMjcyMjUwIiwicGFzc3dvcmRIYXNoIjoiJDJiJDEwJG5HbTQ1dDM3ZVM4QXllQlIvVHN0LmV6emkxalVGbU51WDU3VXNTVjd5U1IzaHlLbE8uOVVlIiwiZmlyc3ROYW1lIjoiRWFybGpvZSIsImxhc3ROYW1lIjoiS2FkaW1hIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9zdGF0aWMudmVjdGVlenkuY29tL3N5c3RlbS9yZXNvdXJjZXMvcHJldmlld3MvMDA1LzU0NS8zMzUvbm9uXzJ4L3VzZXItc2lnbi1pY29uLXBlcnNvbi1zeW1ib2wtaHVtYW4tYXZhdGFyLWlzb2xhdGVkLW9uLXdoaXRlLWJhY2tvZ3J1bmQtdmVjdG9yLmpwZyIsInJvbGUiOiJBRE1JTiIsIm1hbmFnZXJSZXF1ZXN0U3RhdHVzIjoiUEVORElORyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInJlc2V0VG9rZW4iOm51bGwsInJlc2V0VG9rZW5FeHBpcnkiOm51bGwsImlhdCI6MTcyMDI2NjM1NSwiZXhwIjoxNzIwMjY5OTU1fQ.JoVNyc1VGr3QiUDL9XrD50ngHm-7VaGCzXLcEzBuYko
Content-Type: application/json

{
    "userId": "5de20edc-36f1-4388-a2ec-2dc61a571e10"
}

###GET MANAGER REQUESTS
GET http://localhost:3000/api/user/manager/requests
Authorization: Bearer 

###REJECT MANAGER ROLE
POST http://localhost:3000/api/user/reject-manager
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkYTQ1MGE0LTg2ZTItNGRkZC04YjhjLTZhNTIxOTU3ZjhhNyIsImVtYWlsIjoiZWFybGpvZTA2QG91dGxvb2suY29tIiwicGhvbmVOdW1iZXIiOiIrMjU0MTEyMjcyMjUwIiwicGFzc3dvcmRIYXNoIjoiJDJiJDEwJG5HbTQ1dDM3ZVM4QXllQlIvVHN0LmV6emkxalVGbU51WDU3VXNTVjd5U1IzaHlLbE8uOVVlIiwiZmlyc3ROYW1lIjoiRWFybGpvZSIsImxhc3ROYW1lIjoiS2FkaW1hIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9zdGF0aWMudmVjdGVlenkuY29tL3N5c3RlbS9yZXNvdXJjZXMvcHJldmlld3MvMDA1LzU0NS8zMzUvbm9uXzJ4L3VzZXItc2lnbi1pY29uLXBlcnNvbi1zeW1ib2wtaHVtYW4tYXZhdGFyLWlzb2xhdGVkLW9uLXdoaXRlLWJhY2tvZ3J1bmQtdmVjdG9yLmpwZyIsInJvbGUiOiJBRE1JTiIsIm1hbmFnZXJSZXF1ZXN0U3RhdHVzIjoiUEVORElORyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInJlc2V0VG9rZW4iOm51bGwsInJlc2V0VG9rZW5FeHBpcnkiOm51bGwsImlhdCI6MTcyMDI2MjY4OSwiZXhwIjoxNzIwMjY2Mjg5fQ.IGkzifhR5_UWJ77j2z1-s8A9yp92M6B0nl-FMYVADc4
Content-Type: application/json

{
    "userId": "5de20edc-36f1-4388-a2ec-2dc61a571e10"
}
###GET ALL MANAGERS
GET http://localhost:3000/api/user/manager/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxZjFkMjdiMy0zMWY4LTQ0YjktYmU0NC0yNTA2YTVmOTU1YTEiLCJlbWFpbCI6ImVhcmxqb2UwNkBvdXRsb29rLmNvbSIsInBob25lTnVtYmVyIjoiMDExMjI3MjI1MCIsImZpcnN0TmFtZSI6IkVhcmxqb2UiLCJsYXN0TmFtZSI6IkthZGltYSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcyMTM4NjE3NiwiZXhwIjoxNzIxNDAwNTc2fQ.Lt0VuDYdF5xW6vG-m4p591z6wnPQnv0AkULRn0jFiYo

###CHANGE ROLE
POST http://localhost:3000/api/user/change-role
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkYTQ1MGE0LTg2ZTItNGRkZC04YjhjLTZhNTIxOTU3ZjhhNyIsImVtYWlsIjoiZWFybGpvZTA2QG91dGxvb2suY29tIiwicGhvbmVOdW1iZXIiOiIrMjU0MTEyMjcyMjUwIiwicGFzc3dvcmRIYXNoIjoiJDJiJDEwJG5HbTQ1dDM3ZVM4QXllQlIvVHN0LmV6emkxalVGbU51WDU3VXNTVjd5U1IzaHlLbE8uOVVlIiwiZmlyc3ROYW1lIjoiRWFybGpvZSIsImxhc3ROYW1lIjoiS2FkaW1hIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9zdGF0aWMudmVjdGVlenkuY29tL3N5c3RlbS9yZXNvdXJjZXMvcHJldmlld3MvMDA1LzU0NS8zMzUvbm9uXzJ4L3VzZXItc2lnbi1pY29uLXBlcnNvbi1zeW1ib2wtaHVtYW4tYXZhdGFyLWlzb2xhdGVkLW9uLXdoaXRlLWJhY2tvZ3J1bmQtdmVjdG9yLmpwZyIsInJvbGUiOiJBRE1JTiIsIm1hbmFnZXJSZXF1ZXN0U3RhdHVzIjoiUEVORElORyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInJlc2V0VG9rZW4iOm51bGwsInJlc2V0VG9rZW5FeHBpcnkiOm51bGwsImlhdCI6MTcyMDI2MjY4OSwiZXhwIjoxNzIwMjY2Mjg5fQ.IGkzifhR5_UWJ77j2z1-s8A9yp92M6B0nl-FMYVADc4
Content-Type: application/json

{
    "userId": "8bd9ed83-e8df-4913-af10-7855bef50e67",
    "newRole": "ADMIN"
}

###GET USER STATS
GET http://localhost:3000/api/user/u/stats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxZjFkMjdiMy0zMWY4LTQ0YjktYmU0NC0yNTA2YTVmOTU1YTEiLCJlbWFpbCI6ImVhcmxqb2UwNkBvdXRsb29rLmNvbSIsInBob25lTnVtYmVyIjoiMDExMjI3MjI1MCIsImZpcnN0TmFtZSI6IkVhcmxqb2UiLCJsYXN0TmFtZSI6IkthZGltYSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcyMTM4NjE3NiwiZXhwIjoxNzIxNDAwNTc2fQ.Lt0VuDYdF5xW6vG-m4p591z6wnPQnv0AkULRn0jFiYo

###SEARCH USERS
#NOT WORKING
GET http://localhost:3000/api/user/s/search-users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkYTQ1MGE0LTg2ZTItNGRkZC04YjhjLTZhNTIxOTU3ZjhhNyIsImVtYWlsIjoiZWFybGpvZTA2QG91dGxvb2suY29tIiwicGhvbmVOdW1iZXIiOiIrMjU0MTEyMjcyMjUwIiwicGFzc3dvcmRIYXNoIjoiJDJiJDEwJG5HbTQ1dDM3ZVM4QXllQlIvVHN0LmV6emkxalVGbU51WDU3VXNTVjd5U1IzaHlLbE8uOVVlIiwiZmlyc3ROYW1lIjoiRWFybGpvZSIsImxhc3ROYW1lIjoiS2FkaW1hIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9zdGF0aWMudmVjdGVlenkuY29tL3N5c3RlbS9yZXNvdXJjZXMvcHJldmlld3MvMDA1LzU0NS8zMzUvbm9uXzJ4L3VzZXItc2lnbi1pY29uLXBlcnNvbi1zeW1ib2wtaHVtYW4tYXZhdGFyLWlzb2xhdGVkLW9uLXdoaXRlLWJhY2tvZ3J1bmQtdmVjdG9yLmpwZyIsInJvbGUiOiJBRE1JTiIsIm1hbmFnZXJSZXF1ZXN0U3RhdHVzIjoiUEVORElORyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInJlc2V0VG9rZW4iOm51bGwsInJlc2V0VG9rZW5FeHBpcnkiOm51bGwsImlhdCI6MTcyMDI2MjY4OSwiZXhwIjoxNzIwMjY2Mjg5fQ.IGkzifhR5_UWJ77j2z1-s8A9yp92M6B0nl-FMYVADc4
Content-Type: application/json

{
    "search": "h"
}

###DELETE USER
DELETE http://localhost:3000/api/user/8bd9ed83-e8df-4913-af10-7855bef50e67
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkYTQ1MGE0LTg2ZTItNGRkZC04YjhjLTZhNTIxOTU3ZjhhNyIsImVtYWlsIjoiZWFybGpvZTA2QG91dGxvb2suY29tIiwicGhvbmVOdW1iZXIiOiIrMjU0MTEyMjcyMjUwIiwicGFzc3dvcmRIYXNoIjoiJDJiJDEwJG5HbTQ1dDM3ZVM4QXllQlIvVHN0LmV6emkxalVGbU51WDU3VXNTVjd5U1IzaHlLbE8uOVVlIiwiZmlyc3ROYW1lIjoiRWFybGpvZSIsImxhc3ROYW1lIjoiS2FkaW1hIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9zdGF0aWMudmVjdGVlenkuY29tL3N5c3RlbS9yZXNvdXJjZXMvcHJldmlld3MvMDA1LzU0NS8zMzUvbm9uXzJ4L3VzZXItc2lnbi1pY29uLXBlcnNvbi1zeW1ib2wtaHVtYW4tYXZhdGFyLWlzb2xhdGVkLW9uLXdoaXRlLWJhY2tvZ3J1bmQtdmVjdG9yLmpwZyIsInJvbGUiOiJBRE1JTiIsIm1hbmFnZXJSZXF1ZXN0U3RhdHVzIjoiUEVORElORyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMDZUMTA6Mzc6NTQuNDk3WiIsInJlc2V0VG9rZW4iOm51bGwsInJlc2V0VG9rZW5FeHBpcnkiOm51bGwsImlhdCI6MTcyMDI2MjY4OSwiZXhwIjoxNzIwMjY2Mjg5fQ.IGkzifhR5_UWJ77j2z1-s8A9yp92M6B0nl-FMYVADc4
